### ISSUE TITLE
Field returns error if left empty even though field is not required

### ISSUE THREAD

**Issue by davecoggins** [fruitstudios/LinkIt#12] opened 2015-04-16 15:59 UTC
Hi,

I'm having a issue with the following use case. I have LinkIt fields in a team members sections for optional external links to social media accounts. These are all optional and a number of the team members don't have social media accounts to link. However, it doesn't seem possible to save an entry even though the LinkIt field is not set to required. 

Is there an alternative implementation for this use case?

**Comment by veritascs** [comment] 2015-04-22 21:23
Yea I just ran into this too. I'm going to change it locally for now to accept any value (https://github.com/fruitstudios/LinkIt/blob/master/linkit/fieldtypes/Linkit_LinkitFieldType.php#L608).

**Comment by samhibberd** [comment] 2015-04-27 15:34
Ah, this is caused by the request to hide the dropdown when only one type of link is selected for a field.

I will adjust the validation rules so that the custom validation works with the core validation.

Thanks,

Sam

**Comment by seppentoni** [comment] 2015-05-21 14:04
I have this as well. Do I need to hack the core plugin or is there a fix in sight?

**Comment by veritascs** [comment] 2015-06-18 16:31
Not sure...

**Comment by johnwbaxter** [comment] 2015-07-23 09:41
I have this issue also, is there any news on a fix?

**Comment by veritascs** [comment] 2015-07-23 16:31
Not that I know of, use my "fix" I guess.

**Comment by samhibberd** [comment] 2015-09-28 12:18
We have completely rewritten the plugin which is due to be released shortly, no major changes to functionality, just improvements to the code base and the way data is stored and accessed, and much improved validation too which will resolve this issue.

**Comment by veritascs** [comment] 2015-09-28 15:54
Awesome! Can't wait to update and test.

**Comment by shealan** [comment] 2016-02-17 14:17
Hmm, Feb 2015 and this is still an issue. A Linkit field in my form wont submit without throwing an "Please select an entry" error even though the field is not required. Anyone found a solution? Taking the validation out totally isn't really a workable solution for my project.

**Comment by samhibberd** [comment] 2016-02-28 13:53
Fixed in the latest release, please make sure you backup and test out pre launch!

**Closed by samhibberd** 2016-02-28 13:53 UTC
Labels: enhancement
